### ISSUE TITLE
Facing Issue in bulk merge without primary key table

### ISSUE THREAD

**Issue by selva102** [zzzprojects/Bulk-Operations#10] opened 2017-04-03 07:52 UTC
Hi,

 Issue details.

I have "AA" table. in this table I don't have a primary key value. if merge concept will work? other wise how will pass the primary key value in the merge method.

My code:
 BulkOperationManager.BulkOperationBuilder = operation => operation.BatchTimeout = 999999999;
                                if (scrStringOrderByPKCol =="")
                                {
                                    var bulk = new BulkOperation(destinationConnection);
                                    bulk.DestinationTableName = targetTableName;
                                    bulk.BatchSize = batchSize;
                                    bulk.UseInternalTransaction = true;
                                    bulk.DataSource = stagingReader;
                                    bulk.CaseSensitive = CaseSensitiveType.Insensitive;
                                    bulk.BulkMerge();
                                }

This below property will work? 

bulk..ColumnPrimaryKeyExpression ==??????

issue:  
If I am adding the above property means I will face the issue "An error occured while resolving ColumnPrimaryKey expression"

Question:

Without primarykey  bulk.merge will work?

please guide me

**Comment by selva102** [comment] 2017-04-03 09:19
anyone help me on this

**Comment by JonathanMagnan** [comment] 2017-04-03 13:05
Hello Selva,

The merge will still work if you have an identity column. What’s the reason why your table doesn’t have any primary key?

The ColumnPrimaryKeyExpression only work when working with entity

Example:

```csharp
using (var operation = new BulkOperation<Entity>())
{
    operation.ColumnInputExpression = entity => new {entity.ColumnIdentityPK, entity.ColumnIntTest}; 
    operation.ColumnPrimaryKeyExpression = entity => entity.ColumnIdentityPK; 

    // ...Code...
}
```

Currently, you will have to add the mappings for this table:

Example:

```csharp
operation.ColumnMappings.Add("ColumnIdentityPK", true); // PK
operation.ColumnMappings.Add("ColumnIntTest");
```

We will investigate today if we can provide you a solution to only specify the primary key instead of having to set all mappings.

Let me know if I answered correctly to all your questions

Best Regards,

Jonathan

**Comment by selva102** [comment] 2017-04-04 11:19
Hi Jonathan,
Thanks for the update. But my scenario its not working. I am not using static table.  passing the primary key value in dynamic method.

My method:
        public void MoveCoreData(string selectScript, string deleteScript, string deleteScriptStaging, string sourceTableName, string targetTableName, string stagingTableName, int batchSize, int executionID, string coreAPIName, string copyOnly, string IsPurgeEnabled, string scrStringOrderByPKCol ,string batchordercolumn)
{
 var bulk1 = new BulkOperation(destinationConnection);

                                bulk1.BatchSize = 1000;
                                bulk1.DestinationTableName = targetTableName;
                                bulk1.BatchSize = batchSize;
                                bulk1.UseInternalTransaction = true;
                                bulk1.DataSource = stagingReader;
                                    // bulk1.ColumnMappings.Add("batchordercolumn");
                                    // bulk1.ColumnMappings.Add("batchordercolumn", true);
                                    // bulk1.ColumnMappings.Add("Id");
                                    bulk1.BulkMerge();
}

So I am getting the identity value into batchordercolumn.  I am having unique values in batchordercolumn.  so passing the batchordercolumn value in the above bulkmerge() method facing the issues.

Issue 1#:   // bulk1.ColumnMappings.Add("batchordercolumn");
              Column Name: 'batchordercolumn', Valid Value: "id,name,status,first,ExecutionID"
Issue 2#:  // bulk1.ColumnMappings.Add("batchordercolumn", true);
               Cannot insert the value NULL into column 'ExecutionID', table 'SA_SDH.dbo.workerrolebatchorderno1_DLMaSHistory'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
              So the above issue only NULL values transfer to one table to another table. but my table executionid is not null.
Issue3#:   // bulk1.ColumnMappings.Add("Id");
                An error occured, no primary could be found or resolved.
           
My table having the four columns id,firstname,lastname,executionid. without primarykey and id column is identity column.  
 
  As per user requirement we are using without primarykey table.

Please help me . we are not using static tables..bcz every customer requirement has been changes. please let me know. how to do dynamically ..

thanks advance,
selva

**Comment by JonathanMagnan** [comment] 2017-04-04 12:50
Hello @selva102 ,

We will try to come out with a solution today for your scenario

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-04-04 17:54
Hello @selva102 ,

Here is a first version if you specify all columns:

```csharp
using System;
using System.Data;
using System.Data.SqlClient;
using System.Windows.Forms;
using Z.BulkOperations;

namespace Lab.BulkOperations.v451
{
    public partial class Form_Request_DynamicKey : Form
    {
        public Form_Request_DynamicKey()
        {
            InitializeComponent();

            var dt = new DataTable();
            dt.Columns.Add("id", typeof(int));
            dt.Columns.Add("executionid", typeof(int));
            dt.Columns.Add("firstname", typeof(string));
            dt.Columns.Add("lastname", typeof(string));

            for (var i = 0; i < 10000; i++)
            {
                dt.Rows.Add(DBNull.Value, i, "y" + i, "z" + i);
            }

            var reader = dt.CreateDataReader();

            MoveCoreData(reader, null, null, null, null, "Request_DynamicKey", null, 1000, 1, null, null, null, null, "batchordercolumn");
        }

        public void MoveCoreData(IDataReader stagingReader, string selectScript, string deleteScript, string deleteScriptStaging, string sourceTableName, string targetTableName, string stagingTableName, int batchSize, int executionID, string coreAPIName, string copyOnly, string IsPurgeEnabled, string scrStringOrderByPKCol, string batchordercolumn)
        {
            using (var connection = new SqlConnection(My.Config.ConnectionStrings.BulkOperations))
            {
                connection.Open();

                var bulk1 = new BulkOperation(connection);

                bulk1.BatchSize = 1000;
                bulk1.DestinationTableName = targetTableName;
                bulk1.BatchSize = batchSize;
                bulk1.UseInternalTransaction = true;
                bulk1.DataSource = stagingReader;

                bulk1.ColumnMappings.Add("executionid", batchordercolumn == "batchordercolumn");
                bulk1.ColumnMappings.Add("firstname", batchordercolumn == "firstname");
                bulk1.ColumnMappings.Add("lastname", batchordercolumn == "lastname");

                bulk1.BulkMerge();
            }
        }
    }
}
```

We are currently working on a more generic solution that will not force you to specify all columns.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-04-04 18:30
Hello @selva102 ,

The v2.11.15 has been released.

We added a new option `AutoMapKeyName`

Let us know if that's what you were looking for.

Example:

```csharp
using System;
using System.Data;
using System.Data.SqlClient;
using System.Windows.Forms;
using Z.BulkOperations;

namespace Lab.BulkOperations.v451
{
    public partial class Form_Request_DynamicKey : Form
    {
        public Form_Request_DynamicKey()
        {
            InitializeComponent();

            var dt = new DataTable();
            dt.Columns.Add("id", typeof(int));
            dt.Columns.Add("executionid", typeof(int));
            dt.Columns.Add("firstname", typeof(string));
            dt.Columns.Add("lastname", typeof(string));

            for (var i = 0; i < 10000; i++)
            {
                dt.Rows.Add(DBNull.Value, i, "y" + i, "z" + i);
            }

            var reader = dt.CreateDataReader();

            MoveCoreData(reader, null, null, null, null, "Request_DynamicKey", null, 1000, 1, null, null, null, null, "executionid");
        }

        public void MoveCoreData(IDataReader stagingReader, string selectScript, string deleteScript, string deleteScriptStaging, string sourceTableName, string targetTableName, string stagingTableName, int batchSize, int executionID, string coreAPIName, string copyOnly, string IsPurgeEnabled, string scrStringOrderByPKCol, string batchordercolumn)
        {
            using (var connection = new SqlConnection(My.Config.ConnectionStrings.BulkOperations))
            {
                connection.Open();

                var bulk1 = new BulkOperation(connection);

                bulk1.BatchSize = 1000;
                bulk1.DestinationTableName = targetTableName;
                bulk1.BatchSize = batchSize;
                bulk1.UseInternalTransaction = true;
                bulk1.DataSource = stagingReader;

                bulk1.AutoMapKeyName = batchordercolumn;

                bulk1.BulkMerge();
            }
        }
    }
}
```

**Comment by selva102** [comment] 2017-04-05 09:51
Hi JonathanMagnan  ,

Thanks lot Jonathan.  Adding this new property " bulk1.AutoMapKeyName = batchordercolumn;" . Prefectly working for me.. Thanks ... I don't have words to say thanks.


Thanks
selva

**Comment by JonathanMagnan** [comment] 2017-04-05 12:25
Closing Comment: Fix confirmed ;)

**Closed by JonathanMagnan** 2017-04-05 12:25 UTC

**Comment by sagsgr8** [comment] 2019-05-20 05:34
How can I refer multiple columns using AutoMapKeyName ?
