### ISSUE TITLE
InsertIfNotExists does not work as expected

### ISSUE THREAD

**Issue by asktuan** [zzzprojects/Bulk-Operations#47] opened 2019-06-18 18:20 UTC
User table has 2 columns: UserId INT, PRIMARY KEY, LoginName VARCHAR(255)
sourceDt is DataTable and have exact same 2 columns above.
Insert the second time I hit exception "Duplicate entry '108' for key 'PRIMARY'"

                using (var connection = DbAdapter.GetDbConnection(targetProviderName, targetConnString))
                {
                    if(connection.State!= ConnectionState.Open)
                        connection.Open();
                    // Bulk insert
                    using (var bulk = new BulkOperation(connection))
                    {
                        bulk.DestinationTableName = "User";
                        bulk.InsertIfNotExists = true;
                        bulk.ColumnMappings.Add("UserId", true);
                        bulk.ColumnMappings.Add("LoginName");
                        bulk.BulkInsert(sourceDt);
                    }
                }

**Comment by JonathanMagnan** [comment] 2019-06-18 18:34
Hello @asktuan ,

We tried it on our side but everything seems to work.

Here is an online example: https://dotnetfiddle.net/Mc67z6

Which database provider are you using? Perhaps you are using something else than SQL Server.

Best Regards,

Jonathan

**Comment by asktuan** [comment] 2019-06-18 20:20
I'm using MySQL, in fact its MariaDB

**Comment by JonathanMagnan** [comment] 2019-06-18 20:22
Thank,

We will try it for this one, perhaps the options is not implemented yet for this provider

**Comment by asktuan** [comment] 2019-06-18 21:34
Would be perfect if MySQL is implemented. 
We're looking forward to it

**Comment by JonathanMagnan** [comment] 2019-06-20 15:14
Hello @asktuan ,

The v2.15.9 has been released.

Could you try this version and let us know if the issue is now fixed on your side?

**Comment by asktuan** [comment] 2019-06-20 17:27
Works great. InsertIfNotExists now works on MySQL (as well as MariaDB
Thank you Jonathan

**Closed** 2019-06-20 17:41 UTC
