### ISSUE TITLE
Problem on SQLServer when BulkInsert(dataTable)

### ISSUE THREAD

**Issue by Anshem** [zzzprojects/Bulk-Operations#3] opened 2016-11-17 16:10 UTC
Hi, 
I have this error when I'm executing BulkInsert(dataTable) with SQLServer -->
" Must declare the scalar variable "@Table_0". "
After read several documents I think that is probably caused by undeclared variable "@Table_0".

Any Help Please? 

Thanks in advance.

**Comment by zzzprojects** [comment] 2016-11-17 16:16
Hello Anshem,

Thank you for reporting this issue.

You are probably right. This issue is caused by an undeclared variable. However, we are missing some information to reproduce it.

Can you provide us:
- The C# code (The mapping, options, etc, you are using)
- The SQL Generated (you can get it using SQL Profiler)

If you have sensible data, you can send us this information to us: info@zzzprojects.com

We will for sure try to fix it ASAP.

Best Regards,

Jonathan

**Comment by Anshem** [comment] 2016-11-17 17:07
Ok, 
This is my vb code:

```
Public Function InsertBulk(ByVal data As DataTable, ByVal identityColumnName As String, ByVal providerType As ProviderType, ByVal Optional destinationTableName As String = Nothing) As DataTable 
        If data IsNot Nothing Then
            Dim connection As IDbConnection = Nothing
            CreateConnection(connection)
            Dim implementedConnection As Common.DbConnection
            implementedConnection = TryCast(connection, Common.DbConnection)
            If implementedConnection IsNot Nothing Then
                Dim bulk As BulkOperation = New BulkOperation(implementedConnection)
                bulk.CaseSensitive = CaseSensitiveType.Insensitive
                bulk.InsertIfNotExists = True
                bulk.Provider = providerType
                If data.Columns IsNot Nothing AndAlso data.Columns.Count > 0 Then
                    If destinationTableName IsNot Nothing Then
                        bulk.DestinationTableName = destinationTableName
                    Else
                        bulk.DestinationTableName = data.TableName
                    End If                    
                    If String.IsNullOrWhiteSpace(identityColumnName) = False Then                      
                        bulk.ColumnMappings.Add(identityColumnName, ColumnMappingDirectionType.Output)                        
                    End If
                    Dim log As String = String.Empty
                    Try
                        bulk.UseLogDump = True
                        bulk.BulkInsert(data)
                    Catch ex As Exception
                        log = bulk.LogDump.ToString()
                    End Try
                End If
            End If
        End If
        Return data
    End Function
```
And this is the profiler:

```
/* SELECT server information */
SELECT  @@VERSION

/* SELECT table information */
SELECT  DestinationTable.Name AS DestinationName ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsInsertTrigger') = 1 )
        ) AS HasInsertTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsUpdateTrigger') = 1 )
        ) AS HasUpdateTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsDeleteTrigger') = 1 )
        ) AS HasDeleteTrigger
FROM    (SELECT @Table_0 AS Name) AS DestinationTable  
        LEFT JOIN sys.synonyms  AS B ON B.object_id = OBJECT_ID(DestinationTable.Name)
                                                                                                                                                             AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
                                                                                                                                                             AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(B.base_object_name)
ORDER BY DestinationName

/* SELECT column information */
SELECT  DestinationTable.Name AS DestinationName ,
        C.name AS ColumnName ,
        C.column_id AS ColumnOrder ,
        C.precision AS Precision ,
        C.scale AS Scale ,
        C.max_length AS MaxLength ,
        C.collation_name AS Collation ,
        C.Is_Identity AS IsIdentity ,
        ( CASE WHEN EXISTS ( SELECT 1
                             FROM   sys.index_columns AS X
                             WHERE  X.index_id = B.index_id
                                    AND X.object_id = B.object_id
                                    AND X.column_id = C.column_id ) THEN 1
               ELSE 0
          END ) AS IsPrimaryKey ,
        C.system_type_id AS System_Type_Id ,
        LOWER(D.Name) AS TypeName,
        (CASE WHEN E.base_object_name IS NOT NULL THEN 1 ELSE 0 END) AS IsSynonym,
        D.is_user_defined,
        F.name
FROM    (SELECT @Table_0 AS Name) AS DestinationTable
        LEFT JOIN sys.synonyms  AS E ON E.object_id = OBJECT_ID(DestinationTable.Name)
                                                                                                                                                             AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
                                                                                                                                                             AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(E.base_object_name)
        LEFT JOIN sys.indexes   AS B ON B.object_id = A.object_id
                                        AND B.is_primary_key = 1
        INNER JOIN sys.columns  AS C ON C.object_id = A.object_id
        INNER JOIN sys.types    AS D ON D.system_type_id = C.system_type_id
                                     AND D.user_type_id = C.user_type_id
        INNER JOIN sys.schemas AS F ON D.schema_id = F.schema_id
ORDER BY DestinationName ,
        ColumnOrder

```

Thanks.

**Comment by zzzprojects** [comment] 2016-11-17 17:57
That's very weird.

It's possible that 2 SQL is executed ?
- The first one you provided which have the SQL parameter and is valid.
- A second SQL executed which doesn't have any SQL parameter and throw an error

Currently, all possibles scenario seems to lead 2 SQL is generated and for an unknown reason, the first SQL (the one you posted) return more than one table in the second select:

```sql
/* SELECT table information */
SELECT  DestinationTable.Name AS DestinationName ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsInsertTrigger') = 1 )
        ) AS HasInsertTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsUpdateTrigger') = 1 )
        ) AS HasUpdateTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsDeleteTrigger') = 1 )
        ) AS HasDeleteTrigger
FROM    (SELECT @Table_0 AS Name) AS DestinationTable  
        LEFT JOIN sys.synonyms  AS B ON B.object_id = OBJECT_ID(DestinationTable.Name)
                                                                                                                                                             AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
                                                                                                                                                             AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(B.base_object_name)
ORDER BY DestinationName
```

Do you have this issue if you try in other tables?

We are currently checking what could cause this issue but so far, we have no clue.

Best Regards,

Jonathan

**Comment by Anshem** [comment] 2016-11-18 10:14
Hi, 
If I try it with another table, I have the same problem. But, if I use the same code with another provider (MySQL, same schema), this works fine. Unfortunately, I need to use SQL Server, MySQL and Oracle. 

Thanks.

**Comment by zzzprojects** [comment] 2016-11-18 13:12
Hello @Anshem ,

Don't worry. We will found the issue and make it work! It just a little bit hard to replicate on our side.

Can you post the full LogDump returned? Parameters & SQL executed are logged, so this could help us to understand a little bit more what's happening.

Best Regards,

Jonathan

**Comment by Anshem** [comment] 2016-11-21 12:55
Hi, 
Im not sure if you are talking about bulk logdump. (bulk.LogDump returns the same value that SQL Profiler).

LogDump from bulk: 
`-- Executing Command:

/* SELECT server information */
SELECT  @@VERSION

/* SELECT table information */
SELECT  DestinationTable.Name AS DestinationName ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsInsertTrigger') = 1 )
        ) AS HasInsertTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsUpdateTrigger') = 1 )
        ) AS HasUpdateTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       'ExecIsDeleteTrigger') = 1 )
        ) AS HasDeleteTrigger
FROM    (SELECT @Table_0 AS Name) AS DestinationTable  
        LEFT JOIN sys.synonyms  AS B ON B.object_id = OBJECT_ID(DestinationTable.Name)
										AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
										AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(B.base_object_name)
ORDER BY DestinationName

/* SELECT column information */
SELECT  DestinationTable.Name AS DestinationName ,
        C.name AS ColumnName ,
        C.column_id AS ColumnOrder ,
        C.precision AS Precision ,
        C.scale AS Scale ,
        C.max_length AS MaxLength ,
        C.collation_name AS Collation ,
        C.Is_Identity AS IsIdentity ,
        ( CASE WHEN EXISTS ( SELECT 1
                             FROM   sys.index_columns AS X
                             WHERE  X.index_id = B.index_id
                                    AND X.object_id = B.object_id
                                    AND X.column_id = C.column_id ) THEN 1
               ELSE 0
          END ) AS IsPrimaryKey ,
        C.system_type_id AS System_Type_Id ,
        LOWER(D.Name) AS TypeName,
        (CASE WHEN E.base_object_name IS NOT NULL THEN 1 ELSE 0 END) AS IsSynonym,
        D.is_user_defined,
        F.name
FROM    (SELECT @Table_0 AS Name) AS DestinationTable
        LEFT JOIN sys.synonyms  AS E ON E.object_id = OBJECT_ID(DestinationTable.Name)
										AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
										AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(E.base_object_name)
        LEFT JOIN sys.indexes   AS B ON B.object_id = A.object_id
                                        AND B.is_primary_key = 1
        INNER JOIN sys.columns  AS C ON C.object_id = A.object_id
        INNER JOIN sys.types    AS D ON D.system_type_id = C.system_type_id
                                     AND D.user_type_id = C.user_type_id
        INNER JOIN sys.schemas AS F ON D.schema_id = F.schema_id
ORDER BY DestinationName ,
        ColumnOrder

-- @Table_0: [USERS] (Type = String, Size = 7)
-- CommandTimeout:30
-- Executing at 21/11/2016 12:08:38
`

Thanks.

**Comment by zzzprojects** [comment] 2016-11-21 13:59
Thank you,

That is exactly what I was looking for.

- Only one SQL has been executed
- The SQL is valid.
- The parameter @Table_0 is added
> @Table_0: [USERS] (Type = String, Size = 7)

In short, it means everything in our library looks to work fine.

Do your other SQL Command with SQL parameter work without problem? Is there something we should be aware? By example, you are looking a plugin which intercepts SQL command that will be executed on the server?

I'm currently looking if I could find a reason for this behavior on Google.

**Comment by Anshem** [comment] 2016-11-22 16:51
Hello, 
I solved the issue, my problem was that I was using generic SQLOLEDB provider, but this doesn't work. The correct way was using SqlConnection class. Now the application is working.

Thanks for all.

**Comment by zzzprojects** [comment] 2016-11-22 17:11
That's great.

That explain why everything we trying didn't work.

Thank you for letting us know, we will for sure reminder this next time someone get a similar issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment] 2017-01-03 03:49
Closing Comment: Issue resolved by using SqlConnection instead

**Closed by JonathanMagnan** 2017-01-03 03:49 UTC
